-- Seed data for top 100+ Indian online stores
INSERT INTO stores (name, domain, category, logo_url) VALUES 
-- E-commerce / Marketplaces
('Amazon India', 'amazon.in', 'E-commerce', 'https://logo.clearbit.com/amazon.in'),
('Flipkart', 'flipkart.com', 'E-commerce', 'https://logo.clearbit.com/flipkart.com'),
('Tata CLiQ', 'tatacliq.com', 'E-commerce', 'https://logo.clearbit.com/tatacliq.com'),
('JioMart', 'jiomart.com', 'E-commerce', 'https://logo.clearbit.com/jiomart.com'),
('Snapdeal', 'snapdeal.com', 'E-commerce', 'https://logo.clearbit.com/snapdeal.com'),
('Meesho', 'meesho.com', 'E-commerce', 'https://logo.clearbit.com/meesho.com'),
('Shopclues', 'shopclues.com', 'E-commerce', 'https://logo.clearbit.com/shopclues.com'),
('Paytm Mall', 'paytmmall.com', 'E-commerce', 'https://logo.clearbit.com/paytmmall.com'),

-- Fashion / Apparel
('Myntra', 'myntra.com', 'Fashion', 'https://logo.clearbit.com/myntra.com'),
('Ajio', 'ajio.com', 'Fashion', 'https://logo.clearbit.com/ajio.com'),
('Nykaa Fashion', 'nykaafashion.com', 'Fashion', 'https://logo.clearbit.com/nykaafashion.com'),
('Biba', 'biba.in', 'Fashion', 'https://logo.clearbit.com/biba.in'),
('W for Woman', 'wforwoman.com', 'Fashion', 'https://logo.clearbit.com/wforwoman.com'),
('FabIndia', 'fabindia.com', 'Fashion', 'https://logo.clearbit.com/fabindia.com'),
('H&M India', 'hm.com', 'Fashion', 'https://logo.clearbit.com/hm.com'),
('Zara India', 'zara.com', 'Fashion', 'https://logo.clearbit.com/zara.com'),
('Marks & Spencer', 'marksandspencer.in', 'Fashion', 'https://logo.clearbit.com/marksandspencer.in'),
('Lifestyle Stores', 'lifestylestores.com', 'Fashion', 'https://logo.clearbit.com/lifestylestores.com'),
('Shoppers Stop', 'shoppersstop.com', 'Fashion', 'https://logo.clearbit.com/shoppersstop.com'),
('Pantaloons', 'pantaloons.com', 'Fashion', 'https://logo.clearbit.com/pantaloons.com'),
('Max Fashion', 'maxfashion.in', 'Fashion', 'https://logo.clearbit.com/maxfashion.in'),
('Clovia', 'clovia.com', 'Fashion', 'https://logo.clearbit.com/clovia.com'),
('Zivame', 'zivame.com', 'Fashion', 'https://logo.clearbit.com/zivame.com'),
('Nykd', 'nykd.com', 'Fashion', 'https://logo.clearbit.com/nykd.com'),
('XYXX', 'xyxxcrew.com', 'Fashion', 'https://logo.clearbit.com/xyxxcrew.com'),
('Bewakoof', 'bewakoof.com', 'Fashion', 'https://logo.clearbit.com/bewakoof.com'),
('Snitch', 'snitch.co.in', 'Fashion', 'https://logo.clearbit.com/snitch.co.in'),
('The Souled Store', 'thesouledstore.com', 'Fashion', 'https://logo.clearbit.com/thesouledstore.com'),

-- Beauty / Personal Care
('Nykaa', 'nykaa.com', 'Beauty', 'https://logo.clearbit.com/nykaa.com'),
('Purplle', 'purplle.com', 'Beauty', 'https://logo.clearbit.com/purplle.com'),
('Mamaearth', 'mamaearth.in', 'Beauty', 'https://logo.clearbit.com/mamaearth.in'),
('Wow Skin Science', 'buywow.in', 'Beauty', 'https://logo.clearbit.com/buywow.in'),
('Plum Goodness', 'plumgoodness.com', 'Beauty', 'https://logo.clearbit.com/plumgoodness.com'),
('Sugar Cosmetics', 'sugarcosmetics.com', 'Beauty', 'https://logo.clearbit.com/sugarcosmetics.com'),
('Man Matters', 'manmatters.com', 'Beauty', 'https://logo.clearbit.com/manmatters.com'),
('Beardo', 'beardo.in', 'Beauty', 'https://logo.clearbit.com/beardo.in'),
('The Man Company', 'themancompany.com', 'Beauty', 'https://logo.clearbit.com/themancompany.com'),
('Bombay Shaving Company', 'bombayshavingcompany.com', 'Beauty', 'https://logo.clearbit.com/bombayshavingcompany.com'),
('Ustraa', 'ustraa.com', 'Beauty', 'https://logo.clearbit.com/ustraa.com'),
('Kapiva', 'kapiva.in', 'Beauty', 'https://logo.clearbit.com/kapiva.in'),
('mCaffeine', 'mcaffeine.com', 'Beauty', 'https://logo.clearbit.com/mcaffeine.com'),
('BBlunt', 'bblunt.com', 'Beauty', 'https://logo.clearbit.com/bblunt.com'),

-- Electronics
('Reliance Digital', 'reliancedigital.in', 'Electronics', 'https://logo.clearbit.com/reliancedigital.in'),
('Croma', 'croma.com', 'Electronics', 'https://logo.clearbit.com/croma.com'),
('Dell India', 'dell.com', 'Electronics', 'https://logo.clearbit.com/dell.com'),
('Lenovo India', 'lenovo.com', 'Electronics', 'https://logo.clearbit.com/lenovo.com'),
('HP India', 'hp.com', 'Electronics', 'https://logo.clearbit.com/hp.com'),
('Apple India', 'apple.com', 'Electronics', 'https://logo.clearbit.com/apple.com'),
('Samsung India', 'samsung.com', 'Electronics', 'https://logo.clearbit.com/samsung.com'),
('OnePlus India', 'oneplus.in', 'Electronics', 'https://logo.clearbit.com/oneplus.in'),
('Xiaomi India', 'mi.com', 'Electronics', 'https://logo.clearbit.com/mi.com'),
('Realme India', 'realme.com', 'Electronics', 'https://logo.clearbit.com/realme.com'),
('Vivo India', 'vivo.com', 'Electronics', 'https://logo.clearbit.com/vivo.com'),
('Oppo India', 'oppo.com', 'Electronics', 'https://logo.clearbit.com/oppo.com'),
('Boat', 'boat-lifestyle.com', 'Electronics', 'https://logo.clearbit.com/boat-lifestyle.com'),
('Noise', 'gonoise.com', 'Electronics', 'https://logo.clearbit.com/gonoise.com'),
('Boult Audio', 'boultaudio.com', 'Electronics', 'https://logo.clearbit.com/boultaudio.com'),
('Fire-Boltt', 'fireboltt.com', 'Electronics', 'https://logo.clearbit.com/fireboltt.com'),

-- Travel / Flight
('MakeMyTrip', 'makemytrip.com', 'Travel', 'https://logo.clearbit.com/makemytrip.com'),
('Cleartrip', 'cleartrip.com', 'Travel', 'https://logo.clearbit.com/cleartrip.com'),
('Goibibo', 'goibibo.com', 'Travel', 'https://logo.clearbit.com/goibibo.com'),
('Yatra', 'yatra.com', 'Travel', 'https://logo.clearbit.com/yatra.com'),
('EaseMyTrip', 'easemytrip.com', 'Travel', 'https://logo.clearbit.com/easemytrip.com'),
('Abhibus', 'abhibus.com', 'Travel', 'https://logo.clearbit.com/abhibus.com'),
('Redbus', 'redbus.in', 'Travel', 'https://logo.clearbit.com/redbus.in'),
('Oyo Rooms', 'oyorooms.com', 'Travel', 'https://logo.clearbit.com/oyorooms.com'),
('Airbnb India', 'airbnb.co.in', 'Travel', 'https://logo.clearbit.com/airbnb.co.in'),
('Agoda', 'agoda.com', 'Travel', 'https://logo.clearbit.com/agoda.com'),
('Booking.com', 'booking.com', 'Travel', 'https://logo.clearbit.com/booking.com'),
('Ixigo', 'ixigo.com', 'Travel', 'https://logo.clearbit.com/ixigo.com'),

-- Food / Grocery
('Zomato', 'zomato.com', 'Food & Grocery', 'https://logo.clearbit.com/zomato.com'),
('Swiggy', 'swiggy.com', 'Food & Grocery', 'https://logo.clearbit.com/swiggy.com'),
('Dominos India', 'dominos.co.in', 'Food & Grocery', 'https://logo.clearbit.com/dominos.co.in'),
('Pizza Hut India', 'pizzahut.co.in', 'Food & Grocery', 'https://logo.clearbit.com/pizzahut.co.in'),
('BigBasket', 'bigbasket.com', 'Food & Grocery', 'https://logo.clearbit.com/bigbasket.com'),
('Blinkit', 'blinkit.com', 'Food & Grocery', 'https://logo.clearbit.com/blinkit.com'),
('Zepto', 'zeptonow.com', 'Food & Grocery', 'https://logo.clearbit.com/zeptonow.com'),
('EatFit', 'eatfit.in', 'Food & Grocery', 'https://logo.clearbit.com/eatfit.in'),
('Licious', 'licious.in', 'Food & Grocery', 'https://logo.clearbit.com/licious.in'),
('FreshToHome', 'freshtohome.com', 'Food & Grocery', 'https://logo.clearbit.com/freshtohome.com'),

-- Pharmacy / Health
('1mg', '1mg.com', 'Health', 'https://logo.clearbit.com/1mg.com'),
('Netmeds', 'netmeds.com', 'Health', 'https://logo.clearbit.com/netmeds.com'),
('PharmEasy', 'pharmeasy.in', 'Health', 'https://logo.clearbit.com/pharmeasy.in'),
('Apollo Pharmacy', 'apollopharmacy.in', 'Health', 'https://logo.clearbit.com/apollopharmacy.in'),
('Healthkart', 'healthkart.com', 'Health', 'https://logo.clearbit.com/healthkart.com'),

-- Home / Furniture
('Pepperfry', 'pepperfry.com', 'Home & Furniture', 'https://logo.clearbit.com/pepperfry.com'),
('Urban Ladder', 'urbanladder.com', 'Home & Furniture', 'https://logo.clearbit.com/urbanladder.com'),
('IKEA India', 'ikea.com', 'Home & Furniture', 'https://logo.clearbit.com/ikea.com'),
('Wooden Street', 'woodenstreet.com', 'Home & Furniture', 'https://logo.clearbit.com/woodenstreet.com'),
('Wakefit', 'wakefit.co', 'Home & Furniture', 'https://logo.clearbit.com/wakefit.co'),
('SleepyCat', 'sleepycat.in', 'Home & Furniture', 'https://logo.clearbit.com/sleepycat.in'),

-- Footwear / Sports
('Nike India', 'nike.com', 'Sports & Footwear', 'https://logo.clearbit.com/nike.com'),
('Adidas India', 'adidas.co.in', 'Sports & Footwear', 'https://logo.clearbit.com/adidas.co.in'),
('Puma India', 'in.puma.com', 'Sports & Footwear', 'https://logo.clearbit.com/in.puma.com'),
('Reebok India', 'reebok.in', 'Sports & Footwear', 'https://logo.clearbit.com/reebok.in'),
('Decathlon India', 'decathlon.in', 'Sports & Footwear', 'https://logo.clearbit.com/decathlon.in'),
('Cult.fit', 'cult.fit', 'Sports & Footwear', 'https://logo.clearbit.com/cult.fit'),
('Bata India', 'bata.in', 'Sports & Footwear', 'https://logo.clearbit.com/bata.in'),
('Metro Shoes', 'metroshoes.com', 'Sports & Footwear', 'https://logo.clearbit.com/metroshoes.com'),

-- Others / Accessories / Gifting
('Lenskart', 'lenskart.com', 'Accessories', 'https://logo.clearbit.com/lenskart.com'),
('Titan', 'titan.co.in', 'Accessories', 'https://logo.clearbit.com/titan.co.in'),
('FirstCry', 'firstcry.com', 'Baby & Kids', 'https://logo.clearbit.com/firstcry.com'),
('Ferns N Petals', 'fnp.com', 'Gifting', 'https://logo.clearbit.com/fnp.com'),
('IGP', 'igp.com', 'Gifting', 'https://logo.clearbit.com/igp.com'),
('Floweraura', 'floweraura.com', 'Gifting', 'https://logo.clearbit.com/floweraura.com'),
('Vistaprint', 'vistaprint.in', 'Gifting', 'https://logo.clearbit.com/vistaprint.in'),
('GIVA', 'giva.co', 'Jewelry', 'https://logo.clearbit.com/giva.co'),
('CaratLane', 'caratlane.com', 'Jewelry', 'https://logo.clearbit.com/caratlane.com'),
('Melorra', 'melorra.com', 'Jewelry', 'https://logo.clearbit.com/melorra.com'),
('Blue Tokai', 'bluetokaicoffee.com', 'Food & Beverage', 'https://logo.clearbit.com/bluetokaicoffee.com'),
('Sleepy Owl', 'sleepyowl.co', 'Food & Beverage', 'https://logo.clearbit.com/sleepyowl.co'),
('Phool', 'phool.co', 'Gifting', 'https://logo.clearbit.com/phool.co'),

-- Entertainment / Booking
('BookMyShow', 'in.bookmyshow.com', 'Entertainment', 'https://logo.clearbit.com/in.bookmyshow.com')
ON CONFLICT (domain) DO NOTHING;
